### ISSUE TITLE
提高代码的后续可维护性

### ISSUE THREAD

**Issue by Reaper622** [woyasuohen6/bone-detection#2]
Review 代码时，发现有部分重复操作代码：
[sidebar.js](https://github.com/woyasuohen6/bone-detection/blob/master/js/module/sidebar.js)
![image](https://user-images.githubusercontent.com/33031512/57373675-85e22180-71cb-11e9-8dde-54a34b17d4f7.png)

![image](https://user-images.githubusercontent.com/33031512/57373712-98f4f180-71cb-11e9-9248-520c8ad1ffcc.png)

如果是对数组内的内容做相同的操作，推荐使用数组遍历方式，一来在后面如果增加了这个类名为`child`的元素，不需要再来更改对他们进行操作的代码，便于后期维护。重复的代码即不高效，也不美观。 :   )

**Comment by woyasuohen6** [comment]
嗯嗯
当时为了方便就没想这么多
我再把代码优化一下
